### ISSUE TITLE
Using this on Xamarin Forms on iOS gives popup on LinkedIn

### ISSUE THREAD

**Issue by LocalJoost** [xamarin/Xamarin.Auth#176]
I am using this on Xamarin Forms on iOS. I successfully login, but as soon as I navigate away from the login page:
![image](https://cloud.githubusercontent.com/assets/4129183/25700094/5b9187ce-30c6-11e7-8a42-8fcf39077061.png)
Code works fine on Android, access token comes in fine, but I have spent two days now trying to prevent this stupid useless popup appearing. Can this be fixed?

**Comment by DFerenczi** [comment]
BUMP! @moljac I wrote to you about exactly this problem in this thread: https://github.com/xamarin/Xamarin.Auth/issues/151#issuecomment-298005832

but didn't get any real feedback. And I still have the same problem, just at TC i get the token, the email and name but the popup still shows and the UIViewController just stays visible. I've tried setting ShowErrors to false but that doesn't change anything. 

Do you mind investigating or help us investigate the problem? 

/Ferenczi

**Comment by moljac** [comment]
@DFerenczi 
In #151 "Completed Event was not fire in iOS" is in most cases was due to using Native UI (SFSafariViewController) with http[s] schema.

OAuth1Authenticator had some issues I introduced during adding support for WKWebView (in addition to UIWebView), but the reason is I assumed it derives from WebRedirectAuthenticator like OAuth2Authenticator and it does not, from day 1 - 4-5 years ago. I fixed most of that in 1.5.0-alpha-xy (xy in {11,12, 13}), but it needs refactoring for sure.

This error handling was in the code from the beginning most likely with purpose. You know server side can change too and in most cases like this "google oauth native panic" it does.

I need time to debug what Twitter servers return today, but pasted screenshots with full-of-info-reports "spent two days now trying to prevent this stupid useless popup appearing" (from MS MVP/senior-dev) push this issue to the bottom of my priority list. Sorry I have my own frustrations too. Democracy I guess.

> Do you mind investigating or help us investigate the problem?

No. I don't mind investigating and I will try to help you, but for me priorities are to make NativeUI with Forms support stable and released ASAP and this is matter of hours/days.

Latest 1.5.0-alpha-* have support for PDB symbol source servers and GitLink (Windows only), so you might be able to step into the code. Send me feedback if or not it works I need it desperately.

**Comment by DFerenczi** [comment]
@moljac I understand that you are busy with other issues and other stuff in general but not being able to use this component at all on iOS is kind of sad. 

Im using 1.4.1, NOT using native UI, the completed event is fired, I manage to get the access token + profile info (email + name), but the popup still shows. 

As I said I understand and respect that you are busy and will wait until you have the time to prioritize this. But do you have any tips in the meantime that we could try?

**Comment by LocalJoost** [comment]
I got so sick and tired of the problem that I downloaded the sources, found the code that shows popups, commented it out, removed the reference for the binary from the project, used mine in stead and checked in the binary. Wanna know details? I wasted like 3 days on this and was DONE with it.

**Comment by DFerenczi** [comment]
Hmm alright sounds abit like a hustle, but if you're willing to provide me with details then yeah sure!

**Comment by LocalJoost** [comment]
Okay, here’s the deal.


  *   Clone https://github.com/xamarin/Xamarin.Auth.git
  *   Checkout branch portable-bait-and-switch
  *   Go to folder source\Xamarin.Auth.XamarinIOS\PlatformSpecific
  *   Find UIViewControllerEx.cs.
  *   Comment out the first (and only) line in the first method (see below)
  *   Compile for release
  *   Find source\Xamarin.Auth.XamarinIOS\bin\Release\Xamarin.Auth.dll
  *   Place it somewhere in a folder in your project (I used Binaries in the root)
  *   Remove the reference to Xamarin.Auth.dll in your iOS project
  *   Add a reference to your home backed dll.



        public static void ShowError(this UIViewController controller, string title, Exception error, Action continuation = null)
        {
            //ShowError(controller, title, error.GetUserMessage(), continuation);
        }

I hope it will get to the AppStore this way. I realize it’s a kludge, its ugly, but after three days trying all kinds of things I and solutions provided me by the web, twitter and whatnot - I was done with it. My take is – let me handle error display to the user and STFU with regards to the rest 😉

Joost van Schaik

Windows Development MVP
Sent from my Surface Pro 4

"The world as I envision it in my head is such a more interesting place"

**Comment by DFerenczi** [comment]
Thanks for the details! This is way to wierd though, the problem just went away for me right now!?! 

I'm now on the latest alpha version, 1.5.0-alpha-13, but I KNOW I tried this yesterday aswell but now the popup does not show if I set ShowErrors to false?? Tested to downgrade to 1.4.1 and the popup shows again. So strange to me but kind of glad that the bool works since thats been the only problem for me. 

Question for @moljac : How "safe" is the alpha version to use? Or app will soon be published (2 weeks) so will the alpha become stable in time? I know it's hard so say but what do you think? 

Thanks again to @LocalJoost for sharing a solution! You should also maybe try the alpha version. 

/Ferenczi

**Comment by LocalJoost** [comment]
Oh, I forgot to tell. I used the alpha code as base ??

Joost van Schaik

Windows Development MVP
Sent from my Lumia 950XL

"The world as I envision it in my head is such a more interesting place"

**Comment by moljac** [comment]
@LocalJoost

> Oh, I forgot to tell. I used the alpha code as base ??

You should be OK. Code in 1.5.0-alpha has numerous fixes and improvements compared to 1.4.1.

 @DFerenczi 

> This is way to wierd though, the problem just went away for me right now!?!

I fixed few issues in OAuth1Authenticator (used by Twitter) last week. There are still few constructs and "features" which I would not like to touch now, because I have no time right now.

> How "safe" is the alpha version to use? 

IMO very safe, more than 1.4.x

> will the alpha become stable in time? 

for sure.

> I know it's hard so say but what do you think?

I don't think - I know. 8-)
I'm about to publish stable and merge to master. It is matter of hours (writing docs) I might be slowed down by //BUILD streaming 8-)

I suggest you - go with alpha (13 iterations...) Windows platofrms with Xamarin.Forms might have issues.

**Comment by DFerenczi** [comment]
@LocalJoost  Hmm strange.. For me the bool (ShowErrors) is now working and as I said no popups are showing when set to false. 

@moljac alright sounds good! Im using OAuth2 though so i guess the changes to OAuth1 wont affect me right?

**Comment by LocalJoost** [comment]
I am glad it works for you. It did not for me. Maybe some other things have changed, I don’t know 😉

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

**Comment by newky2k** [comment]
@LocalJoost  Can you try this with the latest version of Xamarin.Auth please

Regards

**Comment by newky2k** [comment]
no response after two weeks, closing
