### ISSUE TITLE
FindAccountsForService throws on iOS

### ISSUE THREAD

**Issue by Kukkimonsuta** [xamarin/Xamarin.Auth#370]
### Version

- [ ] nuget version = 1.6.0.4
- [ ] component version = 
  - VisualStudio.16.Preview/16.0.0-pre.3.0+28608.199
  - Xamarin.iOS and Xamarin.Mac SDK   12.6.0.16 (bc9c674)
- [ ] iOS version 12.1.4

### Steps to reproduce

```
var accountStore = AccountStore.Create();
var accounts = accountStore.FindAccountsForService("someid");
```

### Expected behaviour

Not throw.

### Actual behaviour

Exception is thrown:

```
Search/Find FindAccountsForServiceAsync Object reference not set to an instance of an object
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForServiceAsync (System.String serviceId) [0x0007f] in <85539ee049364f3e8d64880a4a42b589>:0 
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForService (System.String serviceId) [0x00000] in <85539ee049364f3e8d64880a4a42b589>:0 
  at ShopApp.iOS.Platform.IdentityStorage.Delete () [0x00007] in D:\Projects\shopapp-mobile\src\ShopApp.iOS\Platform\IdentityStorage.cs:117 
  at ShopApp.iOS.AppDelegate.CheckApplicationFirstLaunch (ShopApp.App application) [0x0001a] in D:\Projects\shopapp-mobile\src\ShopApp.iOS\AppDelegate.cs:111 
  at ShopApp.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00034] in D:\Projects\shopapp-mobile\src\ShopApp.iOS\AppDelegate.cs:34 
```

Inner exception:
```
Object reference not set to an instance of an object
  at Xamarin.Auth.KeyChainAccountStore+<>c.<.cctor>b__12_2 () [0x00042] in <85539ee049364f3e8d64880a4a42b589>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at System.Lazy`1[T].CreateValue () [0x00074] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <56d44aabfc8d4a488316d98c7b91b0b0>:0 
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForServiceAsync (System.String serviceId) [0x00030] in <85539ee049364f3e8d64880a4a42b589>:0 
```

I've tracked the issue down to https://github.com/xamarin/Xamarin.Auth/blob/b4fb1bb5c409e281c6bffad74ea8caba87805ea8/source/Core/Xamarin.Auth.XamarinIOS/AccountStore/KeyChainAccountStore.Aync.cs#L63-L69 where `GetField("True")` returns `null`.

> VS bug [#838824](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/838824)

**Comment by ApppppDevs** [comment]
+1 to this. Seems like an issue with Xamarin.iOS SDK version 12.6 (preview). Downgrading Xamarin.iOS to version 12.2 seems to work.

**Comment by cklenk** [comment]
I got this same error today using VS 2019 Preview v4.1. I will try downgrading the iOS sdk to 12.2.

Thanks!

**Comment by berhir** [comment]
Same issue here with VS 2019 Preview 4.1 SVC1 and Xamarin.iOS 12.6.0.23. 
Is there any workaround besides downgrading?

**Comment by dk-mushiyoke** [comment]
I am able to reproduce this on the official VS 2019 release that came out earlier today (version 8.0 build 3001) with Xamarin iOS 12.6.0.25, I am using the latest Xamarin.Auth version which is 1.6.0.4. 

Exception log:
`System.AggregateException: One or more errors occurred. (Search/Find FindAccountsForServiceAsync Object reference not set to an instance of an object) ---> Xamarin.Auth.AccountStoreException: Search/Find FindAccountsForServiceAsync Object reference not set to an instance of an object ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Auth.KeyChainAccountStore+<>c.<.cctor>b__12_2 () [0x00042] in <85539ee049364f3e8d64880a4a42b589>:0 
  at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x0001c] in <f6fd5b6dc94346cb9547cf7dbf9aa8b2>:0 
--- End of stack trace from previous location where exception was thrown ---

  at System.LazyHelper.ThrowException () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:97 
  at System.Lazy`1[T].CreateValue () [0x0007e] in <f6fd5b6dc94346cb9547cf7dbf9aa8b2>:0 
  at System.Lazy`1[T].get_Value () [0x0000a] in <f6fd5b6dc94346cb9547cf7dbf9aa8b2>:0 
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForServiceAsync (System.String serviceId) [0x00030] in <85539ee049364f3e8d64880a4a42b589>:0 
   --- End of inner exception stack trace ---
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForServiceAsync (System.String serviceId) [0x0007f] in <85539ee049364f3e8d64880a4a42b589>:0 
  at Xamarin.Auth.KeyChainAccountStore.FindAccountsForService (System.String serviceId) [0x00000] in <85539ee049364f3e8d64880a4a42b589>:0 `

**Comment by libin85** [comment]
having the same issue with the latest visual studio 2019 release

**Comment by ali-h2010** [comment]
I started getting the issue after Visual Studio 2019 Update. Xcode and Xamarin are all up to date.

**Comment by santihcc** [comment]
+1. In the meantime, any help where I can find the installer to downgrade Xamarin.iOS to version 12.2?

**Comment by someone1984** [comment]
I have same issue this morning. One solution is to downgrade vs to 2017, I think you can't downgrade only Xamarin.iOS, if someone success, please share solution. Another solution is to use SecureStorage from Xamarin.Essentials instead Xamarin.Auth account store.

**Comment by Redth** [comment]
Folks, we'll take a look at this one, but the correct way forward is to switch to SecureStorage from Xamarin.Essentials as we have deprecated the AccountStore in Xamarin.Auth.

**Comment by Redth** [comment]
Also here's a migration guide to switch to SecureStorage in Xamarin.Essentials: https://github.com/xamarin/Xamarin.Auth/wiki/Migrating-from-AccountStore-to-Xamarin.Essentials-SecureStorage

**Comment by motoko89** [comment]
@Kukkimonsuta Did you manage to fix that line? If yes, could you share your repo?

**Comment by wayousuf** [comment]
@someone1984 don't need to downgrade the VS2019, just downgrade the Xamarin.IOS version to 12.2.1.16, here is the link 
https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-12.2.1.16.pkg

**Comment by someone1984** [comment]
@wayousuf thanks for your suggestion, I tried it right now and it's working. But anyway maybe in future, best solution is replace Xamarin.Auth AccountStore with SecureStorage.

**Comment by JPSiller** [comment]
Hi @Redth 

I'm migrating to secure storage, in Android, I'm already overriding OnRequestPermissionsResult for certain activities using custom request codes. Does this matter when setting Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

Apologies if this is not the right spot to ask this but thought it was good for anyone that wants to migrate too instead of downgrading.

**Comment by motoko89** [comment]
> Folks, we'll take a look at this one, but the correct way forward is to switch to SecureStorage from Xamarin.Essentials as we have deprecated the AccountStore in Xamarin.Auth.

@Redth Does SecureStorage use iOS keychain and Android Keystore? Why's there the need for migration? Also I don't think we can even migrate because this function is crashing

**Comment by aleksandrsmyk** [comment]
I have the same issue. When it will be fixed?

**Comment by ali-h2010** [comment]
I moved to Xamarin Essentials. The only concern was that there are no Account class. You just create a dictionary of keys and strings. But you can always create your own handlers.

**Comment by jcampana** [comment]
Hey folks, how do you migrate to SecureStorage if AccountStore.Create().FindAccountsForService(); throws exception? I am trying to migrate but with this crash is impossible...

**Comment by ali-h2010** [comment]
@jcampana, I didn't migrate. I am not sure actually which scenario will require you to transfer the old keys to a new app. Usually, you ship a new clean app without any old info. 

What i did is install the plugin and follow the api to store, retrieve, and delete the keys.

**Comment by moljac** [comment]
This code was fix/workaround for old bug in iOS. When will it be fixed? 

I'm working on it. Currently trying to resurrect old projects so I can build the code. 

Regarding `AccountStore` OAuth does not specify anything about storing tokens. Storing `access_token` is BAD security practice, so the vNext version of Xamarin.Auth will not have AccountStore for sure. Maybe in something like Xamarin.Auth.Extensions (or Extras) and it will use for sure Essentials.

**Comment by ShravanJ** [comment]
Downgrading to Xamarin.iOS 12.2 worked for me as per @wayousuf’s suggestion but I agree, this is just a temporary fix.

**Comment by JPSiller** [comment]
Is it only AccountStore that is being deprecated or the whole Xamarin.Auth library? It seems SecureStorage uses Account class from Xamarin.Auth so that was confusing. From where to where are the accounts migrated?

**Comment by moljac** [comment]
@JPSiller 
SecureStorage does not use anything from Xamarin.Auth. 

The design goal of Essentials was to have 0 or close to 0 dependencies. Account class is there, because Essentials drew few ideas from older libraries.

Xamarin.Auth was designed and implemented in 2012/2013. Reworked in 2016. It will be minimally maintained (bugfixin), but that is almost all.

**Comment by JPSiller** [comment]
Hi @moljac 

Then does Xamarin.Essentials has it's own Account class? 

From the migration guide
https://github.com/xamarin/Xamarin.Auth/wiki/Migrating-from-AccountStore-to-Xamarin.Essentials-SecureStorage. 

From the migration guide:
"Now, instead, using the helper class you'd write:

await SecureStorageAccountStore.SaveAsync(account, "Facebook");"

That method uses the Xamarin.Auth account class

**Comment by moljac** [comment]
`SecureStorageAccountStore` in the doc is wrapper for both `Xamarin.Auth.Account` and  `Xamarin.Essentials.SecureStorage`. 
Check the snippet in the doc. 
`Xamarin.Auth.AccountStore` from 

https://github.com/xamarin/Xamarin.Auth/tree/master/source/Core/Xamarin.Auth.Common.LinkSource/AccountStore

is used only to migrate existing Xamarin.Auth accounts to new storage in Essentials.
Essentials use `SetAsync(string, string)`, so the trick is to serialze Account to JSON.

**Comment by JPSiller** [comment]
@moljac Ok got it, thanks for the explanation so helper class is completely for migration. 

After that you can use the SecureStorage directly. To migrate in iOS we will need to wait for the fix for this thread right? 

After that, once all our users migrate to a version that utilizes secure storage we can safely remove Xamarin.Auth completely in the our next app release. Is that correct?

**Comment by moljac** [comment]
No problems at all. That's the reason we are here.

> To migrate in iOS we will need to wait for the fix for this thread right?

I think so. But good new. I dusted Xamarin.Auth off, upgraded nugets and everything works. I was a bit afraid of this step. I'm testing right now, so patch/fix might be out soon

**Comment by JPSiller** [comment]
@moljac Awesome, thanks a lot.

**Comment by ngalicoco** [comment]
@moljac So if the fix for Xamarin.Auth is out, do we still need to use Secure Storage with migration helper class, or we can  do it later we upgrade our solution to Xamarin.Essentials secure storage ?

**Comment by tipa** [comment]
I would also appreciate a quick hotfix for this issue as it currently blocks me from releasing an app update. Would love to migrate to SecureStorage but as previously mentioned, it won't work with the current version

**Comment by markradacz** [comment]
+1 
for now downgrading the Xamarin.IOS version to 12.2.1.16 worked

**Comment by ethanyuxinzhang** [comment]
> Also here's a migration guide to switch to SecureStorage in Xamarin.Essentials: https://github.com/xamarin/Xamarin.Auth/wiki/Migrating-from-AccountStore-to-Xamarin.Essentials-SecureStorage


I am trying to use this one. However, it throws the same error at the following line: 

var accountStoreAccounts = AccountStore.Create().FindAccountsForService("Facebook");

Could you please let me know what should I do to get the migration done?

Thanks

**Comment by sschmidTU** [comment]
@tipa you can hotfix the issue by downgrading the IOS SDK to 12.2, as others wrote before.
Just download and execute (install) this:
https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-12.2.1.16.pkg

**Comment by hvaughan3** [comment]
@JPSiller You will want to keep Xamarin.Auth migration code until you can be sure that some majority of users is off of **any of the versions** that previously used AccountStore.

If a user skips the one version that has the AccountStore to Essentials migration code and instead updates to the version after that, the migration code would be gone and the app would no longer work for that user.

**Comment by JPSiller** [comment]
@hvaughan3 That's a good point, I think we'll have to leave it for a while until our analytics tell us 99% of our users are using a secure storage version as you suggested. Thanks. 

Hope the fix is available soon

**Comment by grantkiwi** [comment]
Do we have an ETA for a fix here?  How can I downgrade the iOS from 12.6 to 12.2?

**Comment by grantkiwi** [comment]
I installed the hotfix:  https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-12.2.1.16.pkg

then I got an error about a System.Buffers Filenotfound exception

I'm using VS 2019 on PC (SSH to mac mini)

**Comment by Vijay4657** [comment]
I downgraded the iOS version to 12.0 and 9.0 as well. Still facing the same issue. Any help would be really great.?

**Comment by softsan** [comment]
@rickyaare - so when will the new nuget package out? any ETA? thanks!

**Comment by rickykaare** [comment]
@softsan, I think we need someone from the team approving the pull-request and do the release. 

I was facing the issue with `FindAccountsForService` in an old project, and found the suggested fix after some debugging. 

While we are waiting for a release of Xamarin.Auth you can build the [cfboolean-truehandle](https://github.com/rickykaare/Xamarin.Auth/tree/cfboolean-truehandle) branch yourself and reference this instead of the Xamarin.Auth NuGet package.

**Comment by rickykaare** [comment]
ping @moljac

**Comment by softsan** [comment]
@rickykaare - Thanks.

**Comment by grantkiwi** [comment]
I have just taken easy way and gone back to VS 2017 and working fine

**Comment by ajaybhandiwad** [comment]
@moljac - Thanks a lot.

**Comment by moljac** [comment]
Dear community I beg you for a little bit patience, due to the fact that all artifacts (nugets) must be published via CI system (rules).

And of course due to our other tasks and obligations Xamarin.Auth code is a bit stale, so I need to fix Cake scripts and create Azure DevOps Pipelines. I will add support for VS2019 later on.

Thanks for understanding.

**Comment by lewixlabs** [comment]
> @someone1984 don't need to downgrade the VS2019, just downgrade the Xamarin.IOS version to 12.2.1.16, here is the link
> https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-12.2.1.16.pkg

@wayousuf's solution is the best, for those (like me) having in apps in production already, and cannot risk implementing last minute (great for the future) solution proposed by @Redth 
https://github.com/xamarin/Xamarin.Auth/issues/370#issuecomment-479491900

Please Xamarin team fix this issue on iOS SDK stable channel.

Hi!
Lewix

**Comment by JPSiller** [comment]
@lewixlabs Hi! The solution has already been implemented, this is not a Xamarin.iOS issue but rather the Xamarin.Auth library needed to be upgraded to be compatible with the latest Xamarin.iOS.

Right now, the only thing left to do is for the Xamarin.Auth nuget package to be released so you can easily install it into your projects but per the author some scripts need to be updated so it may take a little bit more to be available. 

If you really need this fix you can checkout the branch and compile the library yourself and you would be able to add the dll manually. 

You can see what was implemented for the fix in here:
https://github.com/xamarin/Xamarin.Auth/pull/376

**Comment by lewixlabs** [comment]
Thank you @JPSiller !

**Comment by mjoconnor1985** [comment]
I'm using Xamarin.iOS 12.2.1.12 and I'm still having the problem.

**Comment by gayko1976** [comment]
Problem still exists with latest SDK, Forms and Auth...
Please fix asap. These kind of bugs are annoying...

**Comment by taublast** [comment]
Having 2 apps to be published that are now just crashing, call this annoying..

**Comment by grantkiwi** [comment]
Do we have an ETA on this.  This is extremely important as we cannot access our info.  Help!!!

**Comment by Janglinator** [comment]
@moljac Is there anything we as a community can do to help?  We depend pretty heavily on this project, and need it running as soon as we can.  I've tried manually building it with no success.

Thanks!

**Comment by daviduren** [comment]
Hi @moljac - Is there any update for releasing this version?

**Comment by JPSiller** [comment]
For anyone waiting for the nuget packages I was able to get around this issue by compiling some of the projects manually and at least for me using (.Net Standard, native iOS and native android) it worked just fine. 

I couldn't compile the Windows Universal ones but anyone using iOS and Android can give it a shot. Please use at your own risk though. (You have to replace both the PCL and native dll for it to work)

You can download the dlls in this link:
https://drive.google.com/file/d/1dUaimw39PM_w-H0leRHPl4DZ9RBAKEHG/view?usp=sharing

Hope this temporarily helps someone.

**Comment by grantkiwi** [comment]
Many thanks Juan.  At least some help with this. Very disappointing!!

**Comment by pettys** [comment]
> Dear community I beg you for a little bit patience, due to the fact that all artifacts (nugets) must be published via CI system (rules).

@moljac This delay is pretty frustrating. Please consider:

- **It's Microsoft's fault.** Our projects were building fine until we updated Visual Studio. As far as I know, all components involved in the problem are built and maintained by Microsoft.
- **There's no easy workaround.** We can't simply backtrack a nuget package; downgrading Xamarin.iOS is tweaky, and is causing other problems now in our build pipeline. ("can't find reference in Xamarin.iOS 0.0.0.0" when deploying to iOS device). I can't pair my VS to the Mac because the pair doesn't allow Xamarin.iOS version mismatches.
- **We can't migrate out of it.** The migration instructions referenced in this thread cannot execute because of this bug.
- **A reasonable time to fix has elapsed.** We're coming up on 3 months since this bug was opened.

In my experience, Xamarin builds are hard enough to get working consistently on all needed platforms as it is. Long-lasting bugs like this on top of the typical headaches really detract from the appeal of the Xamarin platform for me.

**Comment by sschmidTU** [comment]
@pettys just another workaround, but have you tried extracting the methods you need from Xamarin.Auth? Or, as a proper fix, migrating to Xamarin Essentials since Auth is deprecated? Just asking in case it might help.

**Comment by pettys** [comment]
Hi @sschmidTU, thanks for the ideas. The extraction idea might have worked -- I didn't dig into the source enough to know how much effort would be involved in that. After leaving my rant here, I decided to just rip Xamarin.Auth out, put Essentials SecureStorage in its place, and not migrate user settings. I didn't want to force all my users to re-log in on the next app update.  :(  Kinda stinks, but I've already burned up 4-8 hours that I didn't really have to spare working around this bug, and felt it was time to cut my losses and move on.

If I had a few more hours to burn, I'd try your method extraction idea -- thanks for mentioning that.

**Comment by moljac** [comment]
@Janglinator 
> Is there anything we as a community can do to help get a release out?

Thanks a lot. I really appreciate this, but I'm afraid it might burn a lot of your time. 
I'm on a plane to Redmond and am rewriting Cake scripts, so I can build on CI servers. Cake API has changed and Xamarin.Auth scripts depend on some Xamarin Cake utilities (nuget) which use old APIs so builds crash. I have to remove all those dependencies by rewriting Cake script. I hope I will finish it next week, but I cannot promise, because it is quite a lot to do and I'm assigned on other projects.

**Comment by moljac** [comment]
@pettys 
I'm sorry for your problems and I'm trying to find some time and fix this and other Xamarin.Auth issues beside my other tasks. Xamarin.Auth is open source and we need maintainers. Would you like to help? It would help you, us and the whole community. I added Native UI support in 2016 and gave Xamarn.Auth few more years, but now time has changed and I'm assigned to other projects. I remember times when I was able to build locally and drag-n-drop nuget into browser and publish new version. This is gone. We have tons more to do in order to publish packages and updates. Help would be great. Thanks

**Comment by lewixlabs** [comment]
@moljac I can guess how you & your team are busy into many projects.
But this (great) project has a big visibility, it's mentioned also in microsoft docs too, as "official" plugin
https://docs.microsoft.com/it-it/xamarin/xamarin-forms/data-cloud/authentication/oauth
So I think developers expect continuous support & updates.

Anyway reinstalling previous Xamarin iOS SDK saved my day (and i think I won't update it for a while 😁 )

Hi!
Lewix

**Comment by pettys** [comment]
> @pettys ...Would you like to help?

It looks like a good pull request was created almost a month ago. That's pretty good community help.

> We have tons more to do in order to publish packages and updates.

I'm not sure how we, the community, can help with that. Taking on "tons more" -- I'm the lone developer for a startup with limited financial runway whose main product is the app. Just the one-day hit this bug smacked us with is a significant setback. "Tons more" on CI/Cake isn't something I'm in a position to help with. Fixing this project's CI system and releasing the nuget packages seems to like the kind of thing Microsoft should take care of for plugins of this nature.

> I'm assigned to other projects.

@moljac I sympathize with that. For what it's worth, I don't blame you personally -- Microsoft has chosen to resource Xamarin such that: (1) we lack testing so new stuff doesn't break existing stuff, and (2) when stuff like this breaks, we can't fix and release quickly.

In my opinion, a plugin that's been supported and promoted by Microsoft (as @lewixlabs pointed out) should be set up such that (1) this bug would have been caught by CI, and (2) the infrastructure would be in place that when the community sends a good PR, it's released within a week.

So, no hard feelings personally - you gotta do what you're tasked by the machine to do. There were decisions made by others that has lead in this case to many, many hours collectively lost by the pool of resources that Xamarin is trying to serve. Fwiw, it's not just Xamarin -- it's a cultural shift of Microsoft I see in many product areas, I understand it helps them go faster in other areas, but I hope the pendulum swings back to find some balance before too long.

**Comment by lewixlabs** [comment]
https://twitter.com/lewixlabs/status/1126480602943954944
we hope in help of David Ortinau 😉

**Comment by markradacz** [comment]
downgrading to 12.2 no longer works withe latest 12.8 and Xamarin.Auth.AccountStore.FindAccountsForService() still returns "Out of memory exception"

**Comment by lewixlabs** [comment]
https://twitter.com/lewixlabs/status/1131194227533275137

**Comment by Janglinator** [comment]
@markradacz Depending on the urgency of your needs, it might be worth manually installing it.  I used [@JPSiller's manually compiled](https://github.com/xamarin/Xamarin.Auth/issues/370#issuecomment-489140679) binaries, which worked great for me.  It got us up and running, at least until a new version of Xamarin.Auth is release.

Thanks @JPSiller!

**Comment by moljac** [comment]
1.7.0-alpha01 released.

- with fix for this issue
- a lot of older platforms removed
- cake build script needs complete rewrite
- VS2019 not supported completely yet
- build are on CI Azure DevOps

**Comment by moljac** [comment]
Reopening this issue, till release. It has most relevant comments

**Comment by nicolasmab** [comment]
Can confirm that 1.7.0-alpha01 works well in vs2019 (iOS and Android).
Also implemented migration guide with no problems. ( https://aka.ms/xamarin-auth-accountstore-migration-guide ). Migrates accounts smoothly in Android and iOS.

**Comment by moljac** [comment]
@nicolasmab 
1.7.0.0 released

closing this one

**Comment by lewixlabs** [comment]
Thank you guys! Will you update nuget package, right?

**Comment by karak** [comment]
Did anyone download the new version?
I can't and no new packages is here: <https://www.nuget.org/packages/Xamarin.Auth/>

**Comment by shruthiks85** [comment]
Waiting for the nuget package update.

**Comment by MichaelPeter** [comment]
Hey I have 1.7.0 Installed and the error still happens on UWP. The error happend starting from the version where I stored a value.

**Comment by lewixlabs** [comment]
> Waiting for the nuget package update.

Nuget package has been updated and it's available.
Thank you guys! Both iOS & Android versions work!

**Comment by shruthiks85** [comment]
> Waiting for the nuget package update.

Yes the update is available and works. Thank you!

**Comment by drznathou** [comment]
Xamarin.Auth 1.7.0 solve the problem
🍔(づ￣ 3￣)づ
 on iOS 13.1.3 with Xamarin.iOS and Xamarin.Mac SDK 13.6.0.12

**Comment by urastogi885** [comment]
I'm trying to migrate from AccountStore to SecureStorage. I am using the [migration helper class](https://github.com/xamarin/Xamarin.Auth/wiki/Migrating-from-AccountStore-to-Xamarin.Essentials-SecureStorage#migration--helper-class).
It says to do the following to use the migration helper:
```
var accountStoreAccounts = AccountStore.Create().FindAccountsForService("Facebook");

await SecureStorageAccountStore.MigrateAllAccountsAsync("Facebook", accountStoreAccounts);
```
But `FindAccountsForService` throws error because it has been deprecated. How to retrieve data from my old accounts stored using AccountStore?
